### ISSUE TITLE
delete beacon not working

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#44]
I used the bearing and distance tool to remove the last beacon from a chain. 

Select->delete->finish. Dialog closes but beacon not actually deleted. 

Can your repeat @nyakudya?

**Comment by NyakudyaA** [comment]
I tried to delete it straight from the database. I could not. I tried deleting all the materialized views so that I could eliminate the problems. unfortunately, I still could not.

 I probed and probed and looked at the triggers on the beacons table to see what effect they having on the deletion. I dropped the trigger trg_beacons_before_delete and everything works perfectly. could you perhaps comment on this by looking at the above trigger and function fn_beacons_before_delete() to see if it's doing what it is supposed to do

**Comment by gubuntu** [comment]
fn_beacons_before_delete() must return OLD not NEW. I'm fixing the setup script in a commit but you can apply that to existing databases
